ECFN := -ec _keccakf1600_spec_ -ec __keccakf1600_ref -ec _keccakf1600_ref1_ -ec _keccakf1600_avx2_ -ec _keccakf1600_4x_avx2_
JEXT := jinc
SRCS := keccakf1600.jinc
entry: extract
include ../../../../../../Makefile.common

